### ISSUE TITLE
Wrong parameter for Webhook_URL

### ISSUE THREAD

**Issue by a5hay** [Parsely/slackbot#4]
It seems like `webhook_url ` in `alerts.py` is set as 
`webhook: https://hooks.slack.com/services/T12345/example12345`
it needs to be
`webhook_url: https://hooks.slack.com/services/T12345/example12345`
in `config.yaml`

**Comment by a5hay** [comment]
One more note -- I had to add these 2 to my requirements.txt to get it running on my server -- Might not affect affect others, but did affect me
```
requests==2.10.0
tornado==3.1.1
```

**Comment by amontalenti** [comment]
@a5hay Thanks for the report! @hbbtstar will take a look at these issues soon.

**Comment by hbbtstar** [comment]
Hi a5ay! 

Thanks for the heads up on these issues. Closed with the most recent push- I've updated the README and the config generator to put webhook_url instead of webhook as well as ensured requests and tornado are now requirements. Thanks!

**Comment by a5hay** [comment]
thanks guys. keep up the great work!
