### ISSUE TITLE
Yaml not in install requirements

### ISSUE THREAD

**Issue by LeakyBucket** [Parsely/slackbot#6]
Hello, I was installing today on a fresh machine and it turns out that `yaml` is not installed with the `parsely_slackbot` package.  I had to install `pyyaml` separately.

**Comment by hbbtstar** [comment]
Hi there!

Thanks for letting us know- it looks like it's not in install_requires in setup.py. I'll make the required adjustment and push a new version.

Thanks for catching this!

-Xand

**Comment by hbbtstar** [comment]
all set- addressed in v1.1.0
